# docker-compose.yml
version: "3"
services:
  web:
    build: ./
    ports:
      - 3000:80
    environment:
      - NODE_ENV=development
      - PORT=80
      - AWS_ACCESS_KEY_ID=24534
      - AWS_SECRET_ACCESS_KEY=33535

  redis:
    image: "redis"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

